version: '2'
services:
  payload-api:
    build: .
    container_name: payload-api
    working_dir: /home/app/payload-api
    ports:
      - "3000:80"
    environment:
      - PASSENGER_APP_ENV=development
      - RAILS_ENV=development
    volumes:
      - .:/home/app/payload-api
  db:
    image: postgres:9.6
    container_name: db
    environment:
      - POSTGRES_USER=payload
      - POSTGRES_DB=payload-api_development
      - POSTGRES_PASSWORD=secretpassword
