default: &default
  adapter: postgresql
  encoding: unicode
  username: payload
  password: secretpassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: payload-api_development

test:
  <<: *default
  database: payload-api_test

production:
  <<: *default
  database: payload-api_production
  username: payload-api
  password: <%= ENV['PAYLOAD-API_DATABASE_PASSWORD'] %>
